name = "Lunarie X: Zenless"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "413de63c0e5a91aa4df53dbcb5435e812a4cf60b58710926df0acabf9929549e"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
