name = "Lunarie X: Zenless"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7110c23e9563d253a552b1f1e43d69a4bad086dd67fc9b0c785d5caece3dab7"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
