name = "Lunarie X: Zenless"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "564a02339c658c3a62a3fc963a8649a1df4c93a9ae1baf2c37aa121b2c40ba43"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
